
version: '3.2'

services:
        file-copy_pastaX:
            image: "spla/file-copy:${TAG}"
            volumes:
              - "/var/log/:/var/log/"
              - "/mnt/sua_origem/:/watcher_one/watch_folder"
            dns: 10.62.0.101
            environment:
              - TIMEOUT=60
              - DESTINATION=/tmp/

        file-copy_pastaY:
            image: "spla/file-copy:${TAG}"
            volumes:
              - "/var/log/:/var/log/"
              - "/mnt/sua_origem/:/watcher_one/watch_folder"
            dns: 10.62.0.101
            environment:
              - TIMEOUT=60
              - DESTINATION=/tmp/